const nodemailer = require('nodemailer');
const ejs = require('ejs');
const path = require('path');
const archiver = require('archiver');
const fs = require('fs');
require('dotenv').config();

const WEBSITE_URL = process.env.WEBSITE_URL || 'http://www.single-cell-spatial.com';
const CONTACT_EMAIL = process.env.CONTACT_EMAIL || 'bosheng.li@pku-iaas.edu.cn';

function getFunLabel(fun) {
    const map = {
        1: 'Cluster analysis',
        2: 'Single-gene mapping',
        3: 'Multi-gene mapping',
    };
    return map[Number(fun)] || 'Analysis';
}

function getTypeLabel(type) {
    const map = {
        1: 'Single-cell data',
        2: 'Single-cell spatial data',
        3: 'BTSpatial data',
        4: 'Xenium data',
        5: 'H5AD data',
    };
    return map[Number(type)] || 'Custom dataset';
}

function listFilesRecursively(baseDir, currentDir = baseDir) {
    if (!baseDir || !fs.existsSync(currentDir)) {
        return [];
    }

    const entries = fs.readdirSync(currentDir, { withFileTypes: true });
    const files = [];

    for (const entry of entries) {
        const fullPath = path.join(currentDir, entry.name);
        if (entry.isDirectory()) {
            files.push(...listFilesRecursively(baseDir, fullPath));
        } else {
            files.push(path.relative(baseDir, fullPath).replace(/\\/g, '/'));
        }
    }

    return files;
}

function buildHighlights({ fun, type, artifactFiles, counts }) {
    const highlights = [
        `${getFunLabel(fun)} finished successfully for the ${getTypeLabel(type)} workflow.`,
        `The export package contains ${counts.pdf} figure file(s), ${counts.csv} table file(s), and ${counts.other} additional output file(s).`,
        'A compressed result archive is attached so you can download, review, and share the analysis outputs directly.',
    ];

    if (Number(fun) === 1) {
        highlights.push('The result set typically includes clustering visualizations, dimensionality reduction plots, and expression summary tables.');
    } else if (Number(fun) === 2) {
        highlights.push('The result set typically includes single-gene projection views across atlas embeddings and available spatial coordinates.');
    } else if (Number(fun) === 3) {
        highlights.push('The result set typically includes multi-gene projection outputs and comparative views across clusters or spatial regions.');
    } else {
        highlights.push('The result set includes the files generated automatically by the selected analysis pipeline.');
    }

    if (artifactFiles.some((file) => file.toLowerCase().includes('marker'))) {
        highlights.push('Marker-related tables were detected in the exported results.');
    }

    return highlights.slice(0, 4);
}

function buildTemplateData(subject, dirPath, context = {}) {
    const artifactFiles = dirPath ? listFilesRecursively(dirPath) : [];
    const counts = artifactFiles.reduce((acc, file) => {
        const lower = file.toLowerCase();
        if (lower.endsWith('.pdf')) {
            acc.pdf += 1;
        } else if (lower.endsWith('.csv') || lower.endsWith('.tsv')) {
            acc.csv += 1;
        } else {
            acc.other += 1;
        }
        return acc;
    }, { pdf: 0, csv: 0, other: 0 });

    const funLabel = getFunLabel(context.fun);
    const typeLabel = getTypeLabel(context.type);
    const archiveName = context.archiveName || 'result archive';

    return {
        subject,
        title: process.env.EMAIL_TITLE || 'Your analysis export is ready',
        intro: process.env.EMAIL_MESSAGE || 'Your analysis has completed successfully. We have organized the generated figures, tables, and supporting outputs into a downloadable archive attached to this email.',
        summaryHeading: `${funLabel} for ${typeLabel}`,
        summaryText: `The automated pipeline has finished processing your submitted dataset. The attached archive contains the exported analysis outputs generated by the platform, ready for review and downstream use.`,
        stats: [
            { value: funLabel, label: 'Analysis mode' },
            { value: typeLabel, label: 'Dataset type' },
            { value: String(artifactFiles.length || 1), label: 'Exported files' },
            { value: archiveName, label: 'Attached package' },
        ],
        highlights: buildHighlights({
            fun: context.fun,
            type: context.type,
            artifactFiles,
            counts,
        }),
        artifactList: artifactFiles.slice(0, 8),
        attachmentText: artifactFiles.length > 0
            ? 'Below is a preview of the generated deliverables included in the attached archive.'
            : 'The result archive has been attached to this message for convenient download.',
        footerMessage: 'A multimodal spatiotemporal atlas for plant regeneration analysis, presented in the same visual spirit as the platform About page.',
        website: WEBSITE_URL,
        contactEmail: CONTACT_EMAIL,
    };
}

async function createZipArchive(dirPath) {
    const zipFileName = `${new Date().toISOString().split('T')[0]}-${Date.now()}.zip`;
    const zipFilePath = path.join(__dirname, '..', zipFileName);

    const archive = archiver('zip', {
        zlib: { level: 9 },
    });

    const output = fs.createWriteStream(zipFilePath);
    archive.pipe(output);
    archive.directory(path.resolve(dirPath), path.basename(dirPath));

    await new Promise((resolve, reject) => {
        output.on('close', resolve);
        archive.on('error', reject);
        archive.finalize();
    });

    return { zipFileName, zipFilePath };
}

const sendEmail = async (to, dirPath, context = {}) => {
    const subject = process.env.EMAIL_SUBJECT || 'Plant Single Cell Spatial Atlas results';
    let zipFilePath = null;
    let zipFileName = null;

    try {
        if (dirPath) {
            const zipInfo = await createZipArchive(dirPath);
            zipFilePath = zipInfo.zipFilePath;
            zipFileName = zipInfo.zipFileName;
        }

        const smtpHost = process.env.SMTP_HOST || 'smtp.163.com';
        const smtpPort = Number(process.env.SMTP_PORT || 465);
        const smtpSecure = String(process.env.SMTP_SECURE || 'true') !== 'false';

        const transporter = nodemailer.createTransport({
            host: smtpHost,
            port: smtpPort,
            secure: smtpSecure,
            auth: {
                user: process.env.EMAIL_USER,
                pass: process.env.EMAIL_PASS,
            },
        });

        const templatePath = path.join(__dirname, 'templates', 'emailTemplate.ejs');
        const htmlContent = await ejs.renderFile(
            templatePath,
            buildTemplateData(subject, dirPath, {
                ...context,
                archiveName: zipFileName || 'result archive',
            }),
        );

        const mailOptions = {
            from: process.env.EMAIL_FROM || process.env.EMAIL_USER,
            to,
            subject,
            html: htmlContent,
            attachments: zipFilePath ? [
                {
                    filename: zipFileName,
                    path: zipFilePath,
                },
            ] : [],
        };

        const info = await transporter.sendMail(mailOptions);
        console.log(`邮件发送成功: ${info.response}`);
    } catch (error) {
        console.error(`处理邮件时出错: ${error.message || error}`);
        throw error;
    } finally {
        if (zipFilePath && fs.existsSync(zipFilePath)) {
            fs.unlinkSync(zipFilePath);
        }
    }
};

module.exports = sendEmail;
